services:
  db:
    image: postgres:15
    container_name: dolap_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dolap
      POSTGRES_PASSWORD: dolap123
      POSTGRES_DB: dolap
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: