"""add_is_ironed

Revision ID: a17a46cb66ee
Revises: ac052132792f
Create Date: 2026-10-02 16:03:22.108351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17a46cb66ee'
down_revision: Union[str, Sequence[str], None] = 'ac052132792f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothes', sa.Column('is_ironed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothes', 'is_ironed')
    # ### end Alembic commands ###
